Ezpz cu 369rqzn
ezpzcoders-llc/ezpz-coding-ui pull request #24
Opened 2022-11-15 21:49 UTC by KevinLaCarrubba

Will update shortly

2022-11-15 21:49 UTC, arfusop commented
Task linked: [CU-369rqzn Create the Register page](https://app.clickup.com/t/369rqzn)

2022-11-16 16:35 UTC, arfusop requested changes

2022-11-16 16:35 UTC, arfusop commented on utilities/hooks/useForm.ts
> +        // if (validations[name]) {
Remove these comments

2022-11-16 17:19 UTC, arfusop approved these changes

2022-11-16 18:56 UTC, SamiFdev approved these changes

2022-11-16 18:56 UTC, merged