Ezpz cu 369rqzv: Create Forgot Password Page
ezpzcoders-llc/ezpz-coding-ui pull request #30
Opened 2022-11-21 22:01 UTC by KevinLaCarrubba

2022-11-21 22:01 UTC, arfusop commented
Task linked: [CU-369rqzv Create the Forgot Password page](https://app.clickup.com/t/369rqzv)

2022-11-21 22:24 UTC, arfusop requested changes
Few changes, few general comments/questions

2022-11-21 22:36 UTC, KevinLaCarrubba commented on components/views/auth/ForgotPassword.tsx
> +        setAlert({
thats what i figured so i didnt too in depth .. also why i didnt even bother using the loader after i put the code in .

2022-11-21 22:38 UTC, KevinLaCarrubba commented on components/views/auth/ResetPassword.tsx
> +                                showMessage={true}
Clean.

2022-11-21 22:46 UTC, KevinLaCarrubba commented on pages/forgot-password.tsx
> +import ForgotPassword from '../components/views/auth/ForgotPassword'
Fixed.

2022-11-21 22:46 UTC, KevinLaCarrubba commented on components/loader/index.tsx
> +const Loader = () => {
ty ty

2022-11-21 22:49 UTC, KevinLaCarrubba commented on components/views/auth/Login.tsx
> +                            <Link href="/forgot-password">
done

2022-11-21 22:52 UTC, KevinLaCarrubba commented on components/views/auth/ForgotPassword.tsx
> +        VALIDATIONS
Phantom Errors

2022-11-22 21:39 UTC, arfusop approved these changes

2022-11-23 03:39 UTC, SamiFdev approved these changes

2022-11-23 03:43 UTC, merged