Line chart live data hook up
ezpzcoders-llc/ezpz-coding-ui pull request #47
Opened 2022-12-13 17:08 UTC by KevinLaCarrubba

2022-12-13 17:08 UTC, arfusop commented
Task linked: [CU-47mbe0m Add server date to the line chart](https://app.clickup.com/t/47mbe0m)

2022-12-14 01:14 UTC, arfusop requested changes
Few changes. Looking good

2022-12-14 01:14 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +    const { developers } = devHours
Lines 59-60 can be consolidated into one.

```
const { devHours: { developers } } = useSelector((state: any) => state.developerHours)
```

OR

```
const {developers} = useSelector((state:any) => state.developerHours.developers)
```

2022-12-14 01:14 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +    const { developers } = devHours
Not 100% sure the second one will work, so try it out just to see if it does. The first one is more tried and true so it can be the fallback

2022-12-14 01:14 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +    const newDataSource: any = []
So...dont hate me. but looking at this hours later, all of the logic is GREAT. But, the execution is wrong. We don't want something this heavy being re-run every single render. So let's
1. pull in a `useEffect` that runs on `[developers]`
2. bring in `useState` to store the `dataSource`
3. Run all of the logic in the `useEffect` only if there is no `dataSource` set already

2022-12-14 01:14 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +                dataSource={newDataSource}
This will be pulling from the `useState` variable discussed above, `dataSource`

2022-12-16 18:07 UTC, arfusop requested changes

2022-12-16 18:07 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +    const [dataSource, setDataSource] = useState([]) as any[]
`const [dataSource, setDataSource] = useState<[] | null>(null)`

2022-12-16 18:07 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +    const [dataSource, setDataSource] = useState([]) as any[]
default to null. Makes it A LOT easier to use as a check in the useEffect below

2022-12-16 18:07 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +        setDataSource(dataArray)
Nope. Close tho. For now, let's just wrap the logic in an `if`.
```
if (dataSource === null) {
// run all of the logic above
}
```

2022-12-20 15:48 UTC, SamiFdev approved these changes

2022-12-20 18:29 UTC, arfusop reviewed
One issue

2022-12-20 19:25 UTC, arfusop requested changes

2022-12-20 19:25 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +    const formattedDates = chartDateLimit.map((data: any) => {
Didnt notice these on the last review. Move `chartDateLimit` and `formattedDates` into the useEffect as well. They are only ever being used within there, so they should only be declared where they are being used

2022-12-21 02:40 UTC, arfusop commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +        })
❤️

2022-12-21 16:34 UTC, KevinLaCarrubba commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +        })
Ahh okay makes sense . Gotta pay more attention line by line

2022-12-21 19:26 UTC, KevinLaCarrubba commented on components/charts/line-charts/DeveloperHoursLineChart.tsx
> +        })
🚀

2022-12-21 19:32 UTC, arfusop approved these changes

2022-12-21 19:45 UTC, SamiFdev approved these changes

2022-12-21 19:46 UTC, merged